name: template-repo-usage
on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  template-repo-usage:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
